DROP TABLE IF EXISTS competition_results CASCADE;
DROP TABLE IF EXISTS event_participants CASCADE;
DROP TABLE IF EXISTS participants CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS departments CASCADE;
DROP TABLE IF EXISTS portal_users CASCADE;

CREATE TABLE portal_users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(120) NOT NULL,
    mobile VARCHAR(20) UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    role VARCHAR(30) NOT NULL DEFAULT 'coordinator' CHECK (role IN ('admin', 'coordinator', 'student')),
    department_name VARCHAR(100),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE departments (
    department_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(50) UNIQUE NOT NULL CHECK (category_name IN ('Technical', 'Cultural', 'Sports', 'Workshop', 'Other')),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_name VARCHAR(150) NOT NULL,
    department_id BIGINT REFERENCES departments(department_id) ON DELETE SET NULL,
    category_id BIGINT REFERENCES categories(category_id) ON DELETE SET NULL,
    event_date DATE NOT NULL,
    venue VARCHAR(150),
    description TEXT,
    organizer_name VARCHAR(120) NOT NULL,
    is_competition BOOLEAN DEFAULT FALSE,
    created_by BIGINT REFERENCES portal_users(user_id) ON DELETE SET NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE participants (
    participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participant_name VARCHAR(120) NOT NULL,
    roll_number VARCHAR(30) UNIQUE,
    department_id BIGINT REFERENCES departments(department_id) ON DELETE SET NULL,
    year_of_study INT CHECK (year_of_study BETWEEN 1 AND 6),
    participant_type VARCHAR(20) NOT NULL DEFAULT 'Internal' CHECK (participant_type IN ('Internal', 'External')),
    email VARCHAR(120),
    phone VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE event_participants (
    event_participant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(event_id, participant_id)
);

CREATE TABLE competition_results (
    result_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(event_id) ON DELETE CASCADE,
    participant_id BIGINT NOT NULL REFERENCES participants(participant_id) ON DELETE CASCADE,
    rank_position INT,
    award_name VARCHAR(120),
    prize_amount NUMERIC(10, 2) DEFAULT 0,
    remarks TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO departments (department_name) VALUES
('Computer Science'),
('Information Science'),
('Electronics'),
('Mechanical'),
('Civil'),
('MBA'),
('MCA');

INSERT INTO categories (category_name) VALUES
('Technical'),
('Cultural'),
('Sports'),
('Workshop'),
('Other');
